services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  cache:
    image: redis:7.4.1-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
