
services:
  user-service:
    image: akashvai/user-authentication-authorization-service:latest
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - USER_SERVICE.PORT=8888
    ports:
      - "9532:8888"
    networks:
      - user-service-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - user-service-network

networks:
  user-service-network:
    driver: bridge

# Currently cache is not needed. But in future to implement Bloom filter for username validity check we need to implement cache.

#  cache:
#    image: redis:7.4.1-alpine
#    container_name: redis-cache
#    ports:
#      - "6379:6379"