USER_SERVICE:
  DATABASE_USERNAME: "${DATABASE_USERNAME:admin}"
  DATABASE_PASSWORD: "${DATABASE_PASSWORD:password}"
  DATABASE_HOSTNAME: "${DATABASE_HOSTNAME:127.0.0.1}"
  DATABASE_PORT: "${DATABASE_PORT:5432}"
  DATABASE: "${DATABASE_NAME:postgres}"
  SERVER_PORT: "${SERVER_PORT:9532}"
  SECRET_KEY: "${SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}"
  EXPIRATION: "${EXPIRATION:86400000}"
  REFRESH_EXPIRATION: "${REFRESH_EXPIRATION:604800000}"
server:
  port: "${USER_SERVICE.SERVER_PORT}"
  servlet:
    context-path: "/user/cromxt"
spring:
  application:
    name: user
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USER_SERVICE.DATABASE_USERNAME}
    password: ${USER_SERVICE.DATABASE_PASSWORD}
    url: jdbc:postgresql://${USER_SERVICE.DATABASE_HOSTNAME}:${USER_SERVICE.DATABASE_PORT}/${USER_SERVICE.DATABASE}
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 86400