USER_SERVICE:
  DATABASE_USERNAME: "${DATABASE_USERNAME:admin}"
  DATABASE_PASSWORD: "${DATABASE_PASSWORD:password}"
  DATABASE_HOSTNAME: "${DATABASE_HOSTNAME:127.0.0.1}"
  DATABASE_PORT: "${DATABASE_PORT:5432}"
  DATABASE: "${DATABASE_NAME:postgres}"
  SERVER_PORT: "${SERVER_PORT:9532}"
server:
  port: "${USER_SERVICE.SERVER_PORT}"
spring:
  application:
    name: user
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USER_SERVICE.DATABASE_USERNAME}
    password: ${USER_SERVICE.DATABASE_PASSWORD}
    url: jdbc:postgresql://${USER_SERVICE.DATABASE_HOSTNAME}:${USER_SERVICE.DATABASE_PORT}/${USER_SERVICE.DATABASE}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop