USER_SERVICE:
  DATABASE_USERNAME: "${DATABASE_USERNAME:admin}"
  DATABASE_PASSWORD: "${DATABASE_PASSWORD:password}"
  DATABASE_HOSTNAME: "${DATABASE_HOSTNAME:127.0.0.1}"
  DATABASE_PORT: "${DATABASE_PORT:5432}"
  DATABASE: "${DATABASE_NAME:postgres}"
  SERVER_PORT: "${SERVER_PORT:9532}"
  SECRET_KEY: "${SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}"
  EXPIRATION: "${EXPIRATION:900000}"
  REFRESH_EXPIRATION: "${REFRESH_EXPIRATION:1296000000}"
  API_KEY: "${API_KEY:0ABE9EBB93306DB7A19BFBBA4904F014201EDDF53E01651958C89142E5DC67AB06A5FCA7118F530E520837D9A36115B79186021A3D58C8A4CDA19A89A761F1AB}"
server:
  port: "${USER_SERVICE.SERVER_PORT}"
  servlet:
    context-path: "/cromxt"
spring:
  application:
    name: user
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USER_SERVICE.DATABASE_USERNAME}
    password: ${USER_SERVICE.DATABASE_PASSWORD}
    url: jdbc:postgresql://${USER_SERVICE.DATABASE_HOSTNAME}:${USER_SERVICE.DATABASE_PORT}/${USER_SERVICE.DATABASE}
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
