USER_CONFIG_CROMXT_HOME: http://localhost:8500
USER_CONFIG_JWT_SECRET: 9fb6bcf61d009cd62628686c8d46937d32af4c1d624bb0b9ec4e6dcf429d1f3b
USER_CONFIG_JWT_ACCESS_TOKEN_EXPIRATION: 5184000
USER_CONFIG_JWT_REFRESH_TOKEN_EXPIRATION: 77760000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      file-size-threshold: 10MB
      max-request-size: 12 MB
        
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
  web:
    resources:
      static-locations:
      - classpath:/static
server:
  port: 8501
  error:
    whitelabel:
      enabled: false

